### ISSUE TITLE
Biblion images must belong to posts

### ISSUE THREAD

**Issue by holdenweb** [eldarion/biblion#31]
I simply don't understand the rationale for this, when we still have to refer to the image by PK. Why have the relationship at all?

**Comment by paltman** [comment]
I guess it's a matter of opinion but we are generally in favor of having the relationship modeled when one exists. Also, knowing when an Image is used by a post or not allows us to know when it's safe to delete it. Furthermore, you can do things like set the `og:image` open graph tag to the first image of a post.
